// ********************************************************************************
// Kirthi R. Kulkarni
//Date: 4/10/16
// ********************************************************************************
#include <stddef.h>

// *****************************************************************************
// Connector pinout
//                      ____
//               pin 1 |    | pin 10
//               pin 5 |    | pin 6
//   __________________|    |__
//  |                          |    pin 1: VCC (3.3V)
//  |                          |    pin 2: #RESET      <--- Port N6100_LCD_RESET
//  |                          |    pin 3: DATA        <--- Port N6100_LCD_DAT
//  |                          |    pin 4: CLK         <--- Port N6100_LCD_CLK
//  |                          |    pin 5: #CS         <--- Port N6100_LCD_SEL
//  |                          |    pin 6: VCC (3.3V)
//  |                          |    pin 7: N.C.
//  |                          |    pin 8: GND
//  |                          |    pin 9: Backlight -
//  |                          |    pin 10: Backlight + (7-8V)
//  |__________________________|
//
// *****************************************************************************

// *****************************************************************************
// Configuration
// *****************************************************************************


//#include "nokialcd.h"
#include <stdint.h>
#include <stdbool.h>
#include "inc/tm4c123gh6pm.h"
#include "inc/hw_sysctl.h"
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/flash.h"
#include "driverlib/sysctl.h"
#include "driverlib/gpio.h"
#include "driverlib/debug.h"

#define delay_major 1

#define DATA GPIO_PIN_7	    // 3 PIN
#define CLK GPIO_PIN_6		//CLK 5 PIN
#define CS GPIO_PIN_5		//PIN 4
#define SHDN GPIO_PIN_4   ///pin 13

#define	WHITE 0xFFF
#define	BLACK 0x000
#define	RED 0x00F
#define	GREEN 0x0F0
#define	BLUE 0xF00
#define	CYAN 0xFF0
#define	MAGENTA 0xF0F
#define	YELLOW 0x0FF


#define BGCOLOR WHITE
#define FGCOLOR RED
#define SETCON 0x25
#define CASET 0x2A
#define COLMOD 0x3A
#define DISPOFF 0x28
#define DISPON 0x29
#define MADCTL 0x36
#define NOP 0x00
#define PASET 0x2B
#define RAMWR 0x2C
#define SLEEPOUT 0x11
#define INVON 0x20
#define LCD_RESET_LOW GPIOPinWrite(GPIO_PORTC_BASE,CS,0xFF);
#define LCD_RESET_HIGH GPIOPinWrite(GPIO_PORTC_BASE,CS,0x00);

short int a;

//extern unsigned char bitmap[480];
//bmps={ };

/* This is an auto-generated file generated by bmpdump */

/* Array with bitmap containing data of a 130x130 (16900 pixels) image.
 * Each pixel has 12 bits, two pixels share three bytes (RRRRGGGG BBBBRRRR GGGGBBBB).
 */


////////////////////////////////////////////////////////////////////////////////////////////

int mode;

void Delay (unsigned long a)
{
	while (--a!=0);
}

void setbit(unsigned char ch)
{
	GPIOPinWrite(GPIO_PORTC_BASE,ch,0xFF);
}

void resetbit(unsigned char ch)
{
	GPIOPinWrite(GPIO_PORTC_BASE,ch,0x00);
}
//////////////////////////Function to send command to LCD via SPI using bit banging//////////////
void WriteSpiCommand(char command)
{
	resetbit(CLK);
	resetbit(DATA);
	resetbit(CLK);
	setbit(CLK);
	Delay(delay_major);
	resetbit(CLK);
	unsigned char mask=0x80;
	int i;
	for(i=0;i<8;i++)
	{
		if(mask&command)
		{
			setbit(DATA);
		}
		else
		{
			resetbit(DATA);
		}
		mask=mask>>1;
		resetbit(CLK);
		setbit(CLK);
		Delay(delay_major);
		resetbit(CLK);
	}
}
//////////////////////////Function to send data to LCD via SPI using bit banging//////////////
void WriteSpiData(char data)
{
	resetbit(CLK);
	setbit(DATA);
	resetbit(CLK);
	setbit(CLK);
	Delay(delay_major);
	resetbit(CLK);
	unsigned char mask=0x80;
	int i;
	for(i=0;i<8;i++)
	{
		if(mask&data)
		{
			setbit(DATA);
		}
		else
		{
			resetbit(DATA);
		}
		mask=mask>>1;
		resetbit(CLK);
		setbit(CLK);
		Delay(delay_major);
		resetbit(CLK);
	}
}
////////////////////////Function to initialize the LCD screen////////////////////////

void InitLcd(void)
{
	LCD_RESET_LOW;
	Delay(20000);
	LCD_RESET_HIGH;
	Delay(20000);
	WriteSpiCommand(SLEEPOUT);
	//WriteSpiCommand(INVON);
	WriteSpiCommand(COLMOD);
	WriteSpiData(0x03);
	WriteSpiCommand(MADCTL);
	WriteSpiData(0x08);				//48 ///c8
	WriteSpiCommand(SETCON);
	WriteSpiData(0x30);
	Delay(20000);
	WriteSpiCommand(DISPON);

}
////////////////////////Function to clear the LCD screen//////////////////////////////////////
void LCDClearScreen(void)
{

	long i;
	WriteSpiCommand(DISPOFF);
	WriteSpiCommand(PASET);
	WriteSpiData(0);
	WriteSpiData(131);
	WriteSpiCommand(CASET);
	WriteSpiData(0);
	WriteSpiData(131);
	WriteSpiCommand(RAMWR);
	for (i = 0; i < ((131 * 131) / 2); i++)
	{
		WriteSpiData((BLACK >> 4) & 0xFF);
		WriteSpiData(((BLACK & 0xF) << 4) | ((BLACK >> 8) & 0xF)); //Before all were BGCOLOR
		WriteSpiData(BLACK & 0xFF);
		//WriteSpiCommand(NOP);
	}

	WriteSpiCommand(DISPON);
}
////////////////////////Function to set the fore color of text on LCD screen/////////////////////
void LCDforecolor(int x1,int x2, int y1,int y2)
{

	long i;
	LCDClearScreen();
	WriteSpiCommand(DISPOFF);
	WriteSpiCommand(PASET);
	WriteSpiData(x1);
	WriteSpiData(x2);
	WriteSpiCommand(CASET);
	WriteSpiData(y1);
	WriteSpiData(y2);
	WriteSpiCommand(RAMWR);
	for (i = 0; i < ((131 * 131) / 2); i++)
	{
		WriteSpiData((WHITE >> 4) & 0xFF);
		WriteSpiData(((WHITE & 0xF) << 4) | ((WHITE >> 8) & 0xF));//FGCOLOR
		WriteSpiData(WHITE & 0xFF);
	//	WriteSpiCommand(NOP);
	}
	WriteSpiCommand(DISPON);
}

////////// Function to put the image file on the LCD screen////////////////////////
/*void LCDWritebmp(void)
{
	//LCDClearScreen();

	long j;
	WriteSpiCommand(MADCTL);
    WriteSpiData(0xC0); // 48  // 08

    WriteSpiCommand(DISPOFF);
  //  WriteSpiCommand(INVON);
    WriteSpiCommand(CASET);
    WriteSpiData(0);
    WriteSpiData(127);
    WriteSpiCommand(PASET);
    WriteSpiData(0);
    WriteSpiData(127);

    WriteSpiCommand(RAMWR);

    for(j = 0 ; j < 28000 ; j++)
    {
    	WriteSpiData(*(bitmap+j));

    }
	WriteSpiCommand(MADCTL);
    WriteSpiData(0xC0);
    WriteSpiCommand(DISPON);
}
*/
